### ISSUE TITLE
System crash and rebooting with out-land SIM and data roaming disabled

### ISSUE THREAD

**Issue by CaiMiao** [m0m4x/AdvDataPlan#2]
I'm using an dual SIM device, and one of my SIM is foreign SIM and on roaming mode.

I can't really confirm the problem is on dual SIM or roaming SIM so I wrote the title like this.
I can give you more information in case you need.

**Comment by CaiMiao** [comment]
Test again with roaming SIM plugged in only, caused crash.

**Comment by CaiMiao** [comment]
But I can't confirm if the problem is caused by switching to another SIM, as I don't own the third SIM.

**Comment by m0m4x** [comment]
Ok Could you please provide me with the logcat of the error?
Thank you!
Il 16/Ago/2017 17:11 "Fumii Chuu" <notifications@github.com> ha scritto:

**Comment by CaiMiao** [comment]
2017年8月16日 下午11:16，massimo <notifications@github.com>写道：
Ok Could you please provide me with the logcat of the error?
Thanks you!
Il 16/Ago/2017 17:11 "Fumii Chuu" <notifications@github.com> ha scritto:

**Comment by CaiMiao** [comment]
> 08-16 23:38:10.742 I/Xposed  (13922): HOOK NetworkPolicyManager methods! (pkg:com.android.settings)
> 08-16 23:38:10.744 I/Xposed  (13922): HOOK DataUsageSummary methods! (pkg:com.android.settings)!
> 08-16 23:38:11.201 I/Xposed  (13922): HOOK RES init -  com.android.settings !
> 08-16 23:38:11.204 I/Xposed  (13922): HOOK RES       ...found R.layout.data_usage_cycle_editor : 2130968647 !
> 08-16 23:38:13.893 I/Xposed  (13922): HOOK  android.net > computeLastCycleBoundary (pkg:com.android.settings)
> 08-16 23:38:13.894 I/Xposed  (13922): HOOK REQ loaded bitshited Ints 31.0.0
> 08-16 23:38:13.894 I/Xposed  (13922): HOOK REQ LAST Cycle with prefTime:31/01/2017*0  for currentTime:16/08/2017
> 08-16 23:38:23.582 I/Xposed  ( 5752): HOOK RES init -  com.android.settings !
> 08-16 23:38:23.586 I/Xposed  ( 5752): HOOK RES       ...found R.layout.data_usage_cycle_editor : 2130968647 !

Loop same thing like this when I try to open mobile data management on system settings.

**Comment by m0m4x** [comment]
Which Android version/ROM are you running? On which device?

**Comment by m0m4x** [comment]
Please try this build:
https://github.com/m0m4x/AdvDataPlan/blob/issue-2/apk/AdvDataPlan_issue2.apk
Thank you.

**Comment by CaiMiao** [comment]
Android 6.0.1 / cm13-unofficial on Lenovo ZUK Z2

2017年8月17日 上午12:43，massimo <notifications@github.com>写道：

Which Android version/ROM are you running? On which device?

**Comment by CaiMiao** [comment]
This build works for me, and I may have know where the actual problem is!
Ty for your work!
