### ISSUE TITLE
please make it support Android Nougat. Xposed has supported Android Nougat.

### ISSUE THREAD

**Issue by zilinhero** [m0m4x/AdvDataPlan#4]
Please make it support Android Nougat. Xposed has supported Android Nougat.

**Comment by m0m4x** [comment]
preview here:
https://github.com/m0m4x/AdvDataPlan/blob/support-nougat/apk/AdvDataPlan_debug.apk
Some things still need to be done..

edit: update to v1.0.6 - Support for nougat in (experimental release until forst feedback)
https://github.com/m0m4x/AdvDataPlan/blob/support-nougat/apk/AdvDataPlan.apk
or
http://repo.xposed.info/module/net.m0m4x.android.xposed.advdataplan

**Comment by rehannali** [comment]
@m0m4x I installed experimental version which is present in xposed. I can't see text. Please make it visible. There is one other this if it is possible, Can you add time on advance settings like if my plan starts from 2 pm or 5 am etc. I think you can understand it.

**Comment by m0m4x** [comment]
@rehannali  Can you please install the debug version and send me the logcat file at
/data/data/de.robv.android.xposed.installer/log/debug.log and
/data/data/de.robv.android.xposed.installer/log/error.log 
You can find "debug enabled" apk here:
https://github.com/m0m4x/AdvDataPlan/blob/support-nougat/apk/AdvDataPlan_debug.apk
Thank you

**Comment by rehannali** [comment]
@m0m4x debug version is not working. I'm on 7.1.2.

**Comment by m0m4x** [comment]
Please try this 
https://github.com/m0m4x/AdvDataPlan/blob/support-nougat/apk/AdvDataPlan_debug.apk
(previous link was for marshmallow)

**Comment by rehannali** [comment]
[xposed_error_20171024_003211.log](https://github.com/m0m4x/AdvDataPlan/files/1408555/xposed_error_20171024_003211.log)
here is log file.

**Comment by rehannali** [comment]
I cannot see anything with this apk you gave me to install it. I can't even see the advance menu.

**Comment by m0m4x** [comment]
Module was not loaded after installation:
`10-24 00:30:00.793 I/Xposed  (  736): Loading modules from /data/app/net.m0m4x.android.xposed.advdataplan-2/base.apk` 
` 10-24 00:30:00.793 E/Xposed  (  736):   File does not exist` 
Please disable the module from Xposed installer, renable it and then reboot. Let me know.. Thank you.

**Comment by rehannali** [comment]
[xposed_error_20171024_004542.log](https://github.com/m0m4x/AdvDataPlan/files/1408580/xposed_error_20171024_004542.log)
Here it is.

**Comment by rehannali** [comment]
Day to start data usage is blank or black whatever, I don't know exactly. I installed experimental version and encounter with the same problem.

**Comment by m0m4x** [comment]
Seems like data_usage_cycle_editor layout is never been called for inflating..
`resparam.res.hookLayout("com.android.settings", "layout", "data_usage_cycle_editor", new XC_LayoutInflated() { ...`
Do you run Oxygen Os?

**Comment by rehannali** [comment]
AOSP

**Comment by m0m4x** [comment]
Can you please send me a screenshot of the error on telegram? @m0m4x 
Thank you

**Comment by m0m4x** [comment]
@rehannali Issue should be fixed with this update.
https://github.com/m0m4x/AdvDataPlan/raw/support-nougat/apk/AdvDataPlan_debug.apk
